//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IHAComponent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.SpecificComponents = new HashSet<SpecificComponent>();
        }
    
        public int ComponentId { get; set; }

        [Required]
        [Display(Name="Kategori")]
        public int CategoryId { get; set; }

        [Required]
        [Display(Name="Komponent")]
        public string Name { get; set; }

        [DataType(DataType.ImageUrl)]
        [Display(Name="Billed URL")]
        public string Image { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name="Mere info")]
        public string Info { get; set; }

        [DataType(DataType.Url)]
        [Url]
        [Display(Name="Link til datablad")]
        public string Datasheet { get; set; }

        [DataType(DataType.Url)]
        [Url]
        [Display(Name = "Link til producent")]
        public string ManufacturerLink { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(200)]
        [Display(Name="Kommentar")]
        public string AdminComment { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(200)]
        [Display(Name = "Brugerkommentar")]
        public string UserComment { get; set; }
        public byte[] ImageBytes { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificComponent> SpecificComponents { get; set; }
    }
}
