//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IHAComponent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInformation
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name="Udlånsdato")]
        public Nullable<System.DateTime> LoanDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Afleveringsdato")]
        public Nullable<System.DateTime> ReturnDate { get; set; }

        [Display(Name="Send email")]
        public Nullable<bool> IsEmailSend { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Reservationsdato")]
        public Nullable<System.DateTime> ReservationDate { get; set; }

        [Display(Name="Studienr.")]
        public int ReservationId { get; set; }
        public int SpecificComponentId { get; set; }
    
        public virtual SpecificComponent SpecificComponent { get; set; }
        public virtual Student Student { get; set; }
    }
}
