//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IHAComponent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecificComponent()
        {
            this.LoanInformations = new HashSet<LoanInformation>();
        }
    
        public int Id { get; set; }

        [Required]
        [Range(0, 1000)]
        [Display(Name="Komponentnummer")]
        public int Number { get; set; }

        [Display(Name = "Serienr.")]
        public string SerieNr { get; set; }

        [Display(Name = "Komponent")]
        public int Component { get; set; }
    
        public virtual Component Component1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanInformation> LoanInformations { get; set; }
    }
}
