//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IHAComponent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.LoanInformations = new HashSet<LoanInformation>();
        }
    
        public int Id { get; set; }

        [Required]
        [Display(Name="Navn")]
        public string Name { get; set; }

        [Required]
        [Display(Name="Efternavn")]
        public string Efternavn { get; set; }

        [Required]
        [Display(Name = "Studienr.")]
        public string StudentId { get; set; }

        [Display(Name = "Mobilnr.")]
        public string MobileNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanInformation> LoanInformations { get; set; }
    }
}
